version: 2.1

orbs:
  slack: circleci/slack@4.1.1
executors:
  environment:
    docker:
      - image: circleci/golang:1.20
    # working_directory: /go/src/github.com/ralphexp/recipes-api

jobs:
  test:
    executor: environment
    steps:
      - checkout 
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Code linting
          command: >
            go get -u golang.org/x/lint/golint
            #golint ./...
      - run:
          name: Unit tests
          command: | 
            go test -v ./...
            exit 1

  build:
    executor: environment
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Build image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t ralphexp/recipes-api:$TAG --build-arg API_VERSION=${TAG} .
