version: 2.1

executors:
  environment:
    docker:
      - image: circleci/golang:1.15
    working_directory:

jobs:
  test:
    executor: environment
    steps:
      - checkout 
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "api/go.sum" }}
      - run:
          name: Install Dependencies
          command: (cd api && go mod download)
      - save_cache:
          key: go-mod-v4-{{ checksum "api/go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Code linting
          command: >
            # (cd api && go get -u golang.org/x/lint/golint)
            # golint ./...
      - run:
          name: Unit tests
          command: |
            # docker run -d --name redis -p 6379:6379 redis:6.0
            # docker run -d --name mongodb -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password -p 27017:27017 mongod
            # cd api && go test -v ./...
            exit 0

  build:
    executor: environment
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build image
          command: >
            (cd api && docker build -t ralphexp/webapp:latest . )
      - run:
          name: Push image
          command: >
            ( cd api && docker tag ralphexp/webapp:latest
              390844772765.dkr.ecr.us-east-2.amazonaws.com/ralphexp/webapp:$latest )
            ( cd api && docker tag ralphexp/webapp:latest
              390844772765.dkr.ecr.us-east-2.amazonaws.com/ralphexp/webapp:develop )
            ( cd api && docker push 
              390844772765.dkr.ecr.us-east-2.amazonaws.com/ralphexp/webapp:latest )
            ( cd api && docker push 
              390844772765.dkr.ecr.us-east-2.amazonaws.com/ralphexp/webapp:develop )

workflows:
  ci_cd:
    jobs:
      - test
      - build
