version: "3.9" 

services:
  api:
    image: api
    environment:
      - MONGO_URI=mongodb://admin:password@mongodb:27017/test?authSource=admin&readPreference=primary&ssl=false
      - MONGO_DATABASE=demo
      - REDIS_URI=redis:6379
    networks:
      - recipes_network
    external_links:
      - mongodb
      - redis
    scale: 2

  redis:
    image: redis
    networks:
      - recipes_network
    ports:
      - 6379:6379

  mongodb:
    image: mongo:4.4.3
    volumes:
      - /home/mayan/data:/data/db
    networks:
      - recipes_network
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

# we don't have a domain name, but we can add 
# nginx as the reverse proxy, so we can use cookies
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
  #   - dashboard
    networks:
      - recipes_network

networks:
  recipes_network:
